/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SalesforceWrapper {
    }
}
declare global {
    interface HTMLSalesforceWrapperElement extends Components.SalesforceWrapper, HTMLStencilElement {
    }
    var HTMLSalesforceWrapperElement: {
        prototype: HTMLSalesforceWrapperElement;
        new (): HTMLSalesforceWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "salesforce-wrapper": HTMLSalesforceWrapperElement;
    }
}
declare namespace LocalJSX {
    interface SalesforceWrapper {
    }
    interface IntrinsicElements {
        "salesforce-wrapper": SalesforceWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "salesforce-wrapper": LocalJSX.SalesforceWrapper & JSXBase.HTMLAttributes<HTMLSalesforceWrapperElement>;
        }
    }
}
